# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Club.Morse_Siganl_CC.MorseButton import MorseButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("border-radius: 40px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(38, 38, 38, 255), stop:1 rgba(56, 56, 56, 255));\n"
"border-radius: 40px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("background-color: transparent;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_bar_frame = QtWidgets.QFrame(self.main_frame)
        self.title_bar_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar_frame.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(84, 0, 0, 255));")
        self.title_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_frame.setObjectName("title_bar_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_bar_container = QtWidgets.QFrame(self.title_bar_frame)
        self.title_bar_container.setMaximumSize(QtCore.QSize(16777215, 70))
        self.title_bar_container.setStyleSheet("background-color: transparent;")
        self.title_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_container.setObjectName("title_bar_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_bar_container)
        self.horizontalLayout_3.setContentsMargins(30, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_bar = QtWidgets.QLabel(self.title_bar_container)
        self.title_bar.setStyleSheet("font: bold 20px;\n"
"color: rgb(250, 250, 250);")
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_3.addWidget(self.title_bar)
        self.horizontalLayout.addWidget(self.title_bar_container)
        self.tool_box = QtWidgets.QFrame(self.title_bar_frame)
        self.tool_box.setMaximumSize(QtCore.QSize(150, 150))
        self.tool_box.setStyleSheet("background-color: transparent;")
        self.tool_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tool_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tool_box.setObjectName("tool_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tool_box)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeButton = QtWidgets.QPushButton(self.tool_box)
        self.minimizeButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(85, 85, 255);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.minimizeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Assets/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_2.addWidget(self.minimizeButton)
        self.restoreButton = QtWidgets.QPushButton(self.tool_box)
        self.restoreButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(170, 255, 127);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(0, 170, 127);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.restoreButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Assets/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon1)
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_2.addWidget(self.restoreButton)
        self.closeButton = QtWidgets.QPushButton(self.tool_box)
        self.closeButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: ;\n"
"    background-color: rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(208, 0, 0);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Assets/X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.horizontalLayout.addWidget(self.tool_box)
        self.verticalLayout_2.addWidget(self.title_bar_frame)
        self.output_frame = QtWidgets.QFrame(self.main_frame)
        self.output_frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.output_frame.setStyleSheet("background-color: transparent;")
        self.output_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_frame.setObjectName("output_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.output_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_frame = QtWidgets.QFrame(self.output_frame)
        self.text_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.text_frame.setStyleSheet("background-color: transparent;")
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.text_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.text_label = QtWidgets.QLabel(self.text_frame)
        self.text_label.setMinimumSize(QtCore.QSize(70, 0))
        self.text_label.setStyleSheet("font: bold 20px; color : rgb(250, 250, 250);")
        self.text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.text_label.setObjectName("text_label")
        self.horizontalLayout_4.addWidget(self.text_label)
        self.text_entry = QtWidgets.QLineEdit(self.text_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_entry.sizePolicy().hasHeightForWidth())
        self.text_entry.setSizePolicy(sizePolicy)
        self.text_entry.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 20;\n"
"    border-color: rgb(180, 180, 180);\n"
"    font: 20px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.text_entry.setObjectName("text_entry")
        self.horizontalLayout_4.addWidget(self.text_entry)
        self.verticalLayout_3.addWidget(self.text_frame)
        self.morse_frame = QtWidgets.QFrame(self.output_frame)
        self.morse_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.morse_frame.setStyleSheet("background-color: transparent;")
        self.morse_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.morse_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.morse_frame.setObjectName("morse_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.morse_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.morse_label = QtWidgets.QLabel(self.morse_frame)
        self.morse_label.setMinimumSize(QtCore.QSize(70, 0))
        self.morse_label.setStyleSheet("font: bold 20px; color : rgb(250, 250, 250);")
        self.morse_label.setAlignment(QtCore.Qt.AlignCenter)
        self.morse_label.setObjectName("morse_label")
        self.horizontalLayout_5.addWidget(self.morse_label)
        self.morse_entry = QtWidgets.QLineEdit(self.morse_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.morse_entry.sizePolicy().hasHeightForWidth())
        self.morse_entry.setSizePolicy(sizePolicy)
        self.morse_entry.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 20;\n"
"    border-color: rgb(180, 180, 180);\n"
"    font: 20px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.morse_entry.setObjectName("morse_entry")
        self.horizontalLayout_5.addWidget(self.morse_entry)
        self.verticalLayout_3.addWidget(self.morse_frame)
        self.verticalLayout_2.addWidget(self.output_frame)
        self.click_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.click_frame.sizePolicy().hasHeightForWidth())
        self.click_frame.setSizePolicy(sizePolicy)
        self.click_frame.setStyleSheet("background-color: transparent;")
        self.click_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.click_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.click_frame.setObjectName("click_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.click_frame)
        self.horizontalLayout_6.setContentsMargins(30, 0, 30, 55)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_clickme = MorseButton(self.click_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clickme.sizePolicy().hasHeightForWidth())
        self.button_clickme.setSizePolicy(sizePolicy)
        self.button_clickme.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 40px;\n"
"    border-color: rgb(180, 180, 180);\n"
"    font: 35px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 85, 85);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(180, 180, 180);\n"
"    border-color: rgb(180, 180, 180);\n"
"}")
        self.button_clickme.setObjectName("button_clickme")
        self.horizontalLayout_6.addWidget(self.button_clickme)
        self.verticalLayout_2.addWidget(self.click_frame)
        self.verticalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_bar.setText(_translate("MainWindow", "Morse Signal"))
        self.text_label.setText(_translate("MainWindow", "Text"))
        self.morse_label.setText(_translate("MainWindow", "Morse"))
        self.button_clickme.setText(_translate("MainWindow", "Click me"))
import img_rc
